<?php
/**
 * Implements hook_menu_alter().
 */
function dblog_search_menu_alter(&$items) {
  $items['admin/reports/dblog']['page callback'] = 'dblog_overview_extended';
}

function dblog_overview_extended() {
  $rows = array();
  $icons = array(
    WATCHDOG_DEBUG => '',
    WATCHDOG_INFO => '',
    WATCHDOG_NOTICE => '',
    WATCHDOG_WARNING => theme('image', array(
      'path' => 'misc/watchdog-warning.png',
      'width' => '',
      'height' => '',
      'alt' => t('warning'),
      'title' => t('warning'))),
    WATCHDOG_ERROR => theme('image', array(
      'path' => 'misc/watchdog-error.png',
      'width' => '',
      'height' => '',
      'alt' => t('error'),
      'title' => t('error'))),
    WATCHDOG_CRITICAL => theme('image', array(
      'path' => 'misc/watchdog-error.png',
      'width' => '',
      'height' => '',
      'alt' => t('critical'),
      'title' => t('critical'))),
    WATCHDOG_ALERT => theme('image', array(
      'path' => 'misc/watchdog-error.png',
      'width' => '',
      'height' => '',
      'alt' => t('alert'),
      'title' => t('alert'))),
    WATCHDOG_EMERGENCY => theme('image', array(
      'path' => 'misc/watchdog-error.png',
      'width' => '',
      'height' => '',
      'alt' => t('emergency'),
      'title' => t('emergency'))),
  );
  $classes = array(
    WATCHDOG_DEBUG => 'dblog-debug',
    WATCHDOG_INFO => 'dblog-info',
    WATCHDOG_NOTICE => 'dblog-notice',
    WATCHDOG_WARNING => 'dblog-warning',
    WATCHDOG_ERROR => 'dblog-error',
    WATCHDOG_CRITICAL => 'dblog-critical',
    WATCHDOG_ALERT => 'dblog-alert',
    WATCHDOG_EMERGENCY => 'dblog-emerg',
  );

  $form = drupal_get_form('dblog_filter_form');
  $output = drupal_render($form);

  $header = array(
    ' ',
    array(
      'data' => t('Type'),
      'field' => 'w.type',
    ),
    array(
      'data' => t('Date'),
      'field' => 'w.wid',
      'sort' => 'desc',
    ),
    t('Message'),
    array(
      'data' => t('User'),
      'field' => 'u.name',
    ),
    array('data' => t('Operations')),
  );

  $sql = db_select('watchdog', 'w')
  ->extend('TableSort')
    ->orderByHeader($header)
  ->extend('PagerDefault')
    ->limit(50);
  $sql->innerJoin('users', 'u', 'w.uid = u.uid');
  $sql->fields('w', array('wid', 'uid', 'severity', 'type', 'timestamp', 'message', 'variables', 'link', 'hostname'))
  ->fields('u', array('name'));
  $sql = dblog_build_search_query($sql);
  $result = $sql->execute();

  foreach ($result as $dblog) {
    $rows[] = array(
      'data' => array(
        // Cells
        $icons[$dblog->severity],
        t($dblog->type),
        format_date($dblog->timestamp, 'short'),
        l(truncate_utf8(dblog_format_message($dblog), 56, TRUE, TRUE), 'admin/reports/event/' . $dblog->wid, array('html' => TRUE)),
        theme('username', array('account' => $dblog)) . '/' . $dblog->hostname,
        $dblog->link,
      ),
      // Attributes for tr
      'class' => array("dblog-" . preg_replace('/[^a-z]/i', '-', $dblog->type) . ' ' . $classes[$dblog->severity]),
    );
  }

  if (!$rows) {
    $rows[] = array(array(
        'data' => t('No log messages available.'),
        'colspan' => 6,
      ));
  }

  $output .= theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => array('id' => 'admin-dblog')));
  $output .= theme('pager', array('tags' => NULL, 'element' => 0));

  return $output;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dblog_search_form_dblog_filter_form_alter(&$form, &$form_state, $form_id) {
  $form['overview_search'] = array(
    '#type' => 'fieldset',
    '#title' => t('Search'),
  );
  $form['overview_search']['overview_search_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Search user'),
    '#default_value' => isset($_SESSION['overview_search_text']) ? $_SESSION['overview_search_text'] : '',
  );
  $form['overview_search']['overview_search_submit'] = array(
    '#type' => 'submit',
    '#default_value' => t('Search'),
  );

  $form['#submit'][] = 'dblog_filter_search_submit';
}

function dblog_filter_search_submit($form, &$form_state) {
  $_SESSION['overview_search_text'] = $form_state['values']['overview_search_text'];
}

function dblog_build_search_query($sql) {
  if (isset($_GET['link'])) {
    $sql->condition('w.link', $_GET['link']);
  }
  if (isset($_GET['type'])) {
    $sql->condition('w.type', $_GET['type']);
  }
  if (empty($_SESSION['overview_search_text'])) {
    return $sql;
  }
  $sql->condition(db_or()
    ->condition('w.hostname', '%%' . $_SESSION['overview_search_text'] . '%%', 'LIKE')
    ->condition('u.name', '%%' . $_SESSION['overview_search_text'] . '%%', 'LIKE')
  );
  return $sql;
}

function dblog_format_message($dblog) {
  // Legacy messages and user specified text
  if ($dblog->variables === 'N;') {
    return $dblog->message;
  }
  // Message to translate with injected variables
  else {
    return t($dblog->message, unserialize($dblog->variables));
  }
}
